services:
  rabbitmq-test:
    image: rabbitmq:3-management
    ports:
      - "${RABBITMQ_PORT:-5682}:5672"
      - "${RABBITMQ_UI_PORT:-15682}:15672"
    env_file:
      - ./.env.test
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-admin}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS:-admin}
      - RABBITMQ_DEFAULT_VHOST=/
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - dev-test-network
  postgres-test:
    image: postgres:16
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    env_file:
      - ./.env.test
    volumes:
      - postgres-test-data:/var/lib/postgresql/data
    networks:
      - dev-test-network

  redis-test:
    image: redis:7-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "${REDIS_PORT:-6380}:6379"
    env_file:
      - ./.env.test
    volumes:
      - redis-test-data:/data
    networks:
      - dev-test-network

  pgadmin-test:
    image: dpage/pgadmin4:8.12.0
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-test-data:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5052}:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1G
    depends_on:
      postgres-test:
        condition: service_healthy
    networks:
      - dev-test-network

networks:
  dev-test-network:
    driver: bridge

volumes:
  postgres-test-data:
  redis-test-data:
  pgadmin-test-data:
